config/routes.rb
Rails.application.routes.draw do
  
  root 'posts#index'
  get 'aboutme/index'
  get 'aboutme/contact'

  devise_for :users
  
  resources :posts do 
    member do
      put "like", to: "posts#like"
      put "unlike", to: "posts#unlike"
    end
    resources :comments
  end
  

  

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many:posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_attached_file :image, styles: { medium: "600x600>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    
     belongs_to :user
     has_many :comments
     has_many :likes
     belongs_to:category

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_attached_file :image, styles: { thumb: "80x80>",mini: "25x25>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/    
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts    
  has_many :comments
  has_many :likes
end

app/controllers/aboutme_controller.rb
class AboutmeController < ApplicationController
  before_action :index,:contact
  
  def index
  end
  
  def contact
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if:  :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])
  end
  
  before_action :set_locale
  
  def set_locale
    I18n.locale=params[:locale]||I18n.default_locale
  end
  
  def default_url_options (options={})
    {locale: I18n.locale}
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_post

  # GET /comments
  # GET /comments.json
  def index
    @comments = @post.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comments=@post.comments.all
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.build(comment_params)   
    @comment.user= current_user
    
    respond_to do |format|
      if @comment.save
        format.js
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post=Post.find(params[:post_id])
    end
    
    def set_comment
      @comment = @post.comments.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:bdy)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :kontrol,:like, :unlike]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :kontrol, only:[:edit, :destroy]
  before_action :checkadmin, only:[:new,:create]

  def kontrol
    redirect_to posts_path, notice:"Yetkiniz yok!" unless current_user==@post.user
  end
  
  def checkadmin
    @is_admin=User.where(email:'ylmazmehmet60@gmail.com').first
      redirect_to posts_path, notice:"Yetkiniz yok!" unless current_user==@is_admin
  end
  
  
  # GET /posts
  # GET /posts.json
  def index
    if params[:category].blank?
      @posts = Post.all.order("created_at DESC").paginate(page: params[:page], per_page:3) 
	    @posts2 = Post.all.order("created_at DESC")
	    @cat= Category.all.order("created_at DESC")
    else
	    @category_id=Category.find_by(name: params[:category]).id
      @posts = Post.where(category_id:@category_id).order("created_at DESC").paginate(page: params[:page], per_page:3)  
	    @posts2 = Post.all.order("created_at DESC")
	    @cat= Category.all.order("created_at DESC")
    end
    @post=Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     @likeds=Like.where(post: @post).all
     @comments=@post.comments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user=current_user
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def like
    @l=Like.new
    @l.post=@post
    @l.user=current_user
    @l.save
    respond_to do |format|
      format.js {render layout: false}
      format.json
    end
  end

  def unlike
    @l=Like.where(post:@post,user:current_user).first
    @l.destroy
    respond_to do |format|
      format.js {render layout: false}
      format.json
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
      
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :msg, :image, :category_id)
    end
end

app/helpers/aboutme_helper.rb
module AboutmeHelper
end

app/helpers/application_helper.rb
require 'redcarpet'

module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer:language)
    end
  end

  def markdown(msg)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(msg).html_safe
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    
end

app/views/aboutme/contact.html.erb
<div class="container"><br>
   <div class="well">
     <div class="container">
  <div class="row">
    <div class="skinny_wrapper wrapper_padding">
      <h1 id="page_title">İletişim</h1><hr>
          <div class="form-group">
              <label>Başlık</label><br>
             <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="başlık gir">
          </div>
          
          <div class="form-group">
              <label>Konu</label><br>
             <textarea  class="form-control" id="exampleFormControlTextarea1" placeholder="konu gir" rows="9"></textarea >
          </div>
          
          <div class="form-group">
              <label>email</label><br>
             <input type="text" class="form-control" id="exampleFormControlTextarea1" placeholder="email gir" rows="9">
          </div>

          
          <div class="actions">
            <input type="button" value="MESAJ GONDER" class="btn btn-block btn-default btn-md" %>
          </div>
          
      <%= link_to 'Geri', posts_path %><br>
    </div>
  </div>
</div>    
    </div>      
</div> 

<%= render 'shared/footer'%>

app/views/aboutme/index.html.erb
<div class="container"><br>
   <div class="well">
     <div class="wrapper clearfix">
	<div class="col-1 homepage_content">
		<h2>Hakkımda</h2>
		<hr>
		<p>My name is Mehmet Yılmaz.I am twenty-one years old.
		I have been studying Software Engineering at Firat Universitesi in Elazığ. I’m interested programming-my job in future-,engineering math-I really love- and designing-my work entered rare world gallery in this area- so 
		My purposes I am going to publish posts on this blog.
		There are going to be able to fine about both repeating and learning something new besides I am going to improve my english level.</p>
	</div>	
	<div class="col-2 homepage_content">
		<h2>Neler Yapıyorum?</h2>
        <hr>
        <h3>yaptıklarımın listesi</h3>
        <p class="date">Programming</p>
        <p class="date">Designing</p>
        <p class="date">Calculus</p>
	</div>
	<div class="col-3 homepage_content">
        <h2>Programlama dilleri ve araçlar</h2>
        <hr>
        <p>Java</p>
        <p>PHP</p>
        <p>MySQL</p>
        <p>Ruby on Rails</p>
        <p>CakePHP</p>
        <p>3dsMax</p>
        <p>JavaScript</p>
        <p>CSS</p>
        <p>Bootstrap</p>
        <p>C#</p>
        <p>Android Studio</p>
        <p>MVC</p>
        <p>Hackintosh</p>

	</div>

</div>
    </div>      
</div> 

<%= render 'shared/footer'%>

app/views/comments/_form.html.erb
<div class="row">
<div class="col-md-6">
<%= form_for([@post, Comment.new], :remote=>'true', :controller => 'comments', :action => 'create') do |f| %>
<div class="row">
 <div class="col-md-9">
  <div class="form-group">
    <%= f.text_area :bdy, id: :comment_bdy, class:"form-control" ,style:"width:300px; height:50px;"%>
  </div>
  </div>
  <div class="col-md-5">
  <div class="actions">
    <%= f.submit "Yorum At", class:"form-action btn btn-primary" ,style:"width:300px; height:30px;" %>
  </div>
</div>
</div>
<% end %>
</div>
</div>

app/views/comments/create.js.erb
$('#comments').append('<%=image_tag @comment.user.image.url(:mini) if @comment.user.image? %> <em><%=@comment.user.name%> </em> <b> <%=@comment.bdy%> </b><br/>');

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Bdy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.bdy %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bdy:</strong>
  <%= @comment.bdy %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>THEYILMAZ'S</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.0/css/font-awesome.css" rel="stylesheet"> 
</head>
<body>

<%= render 'shared/nav'%>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="skinny_wrapper wrapper_padding">
      <h1 id="page_title">İçerik Yükle!</h1>
      <h3 id="page_title">yazılarınız değerlendirmeye alındıktan sonra yayımlanır.</h3><hr>
      
          <div class="form-group">
             <label>Katogori Seç</label><br>
             <%= f.collection_select :category_id, Category.all, :id, :name, {promt: "Katogori Seç"}	%>
          </div>
      
      
      
          <div class="form-group">
              <label>Başlık</label><br>
             <%= f.text_field :title,class:"form-control",id:"exampleFormControlInput1",placeholder:"başlık gir"%>
          </div>
          
          <div class="form-group">
              <label>İçerik</label><br>
             <%= f.text_area :msg,class:"form-control",id:"exampleFormControlTextarea1",placeholder:"içerik gir" ,rows:"9"%>
          </div>
          
          <div class="form-group">
              <label>İçerik Resmi</label><br>
             <%= f.file_field :image,class:"form-control",id:"exampleFormControlTextarea1",placeholder:"post resmi yükle"%>
          </div>
          
          <div class="actions">
            <%= f.submit 'POSTLA', class: "btn btn-block btn-default btn-md" %>
          </div>
          
      <%= link_to 'Geri', posts_path %><br>
    </div>
  </div>
</div>    
<% end %>

app/views/posts/edit.html.erb
<div class="container"><br>
   <div class="well">
     <%= render 'form' %>
    </div>      
</div> 

<p id="notice"><%= notice %></p>
<%= render 'shared/footer'%>

app/views/posts/index.html.erb
<div class="container"><br>
  <div class="jumbotron">
    <h1 class="display-3">Trust yourself and step forth...</h1>
    <p class="lead">Dünyada paylaştığın her şeyde sana düşen pay azalır. Paylaştıkça çoğalan yegane şey bilgidir. 
      Bu vesile ile okurlara selam ederim.</p>
    <hr class="my-4">
    <p>Bu sitenin kaynak kodlarına GitLab sayfamdan ulaşabilirsiniz... </p>
    <p class="lead">
      <a class="btn btn-primary btn-lg" href="https://gitlab.com/ylmazmehmet60" role="button">Ziyaret Et</a>
    </p>
  </div>
  <div class="row">
    <div class="col-md-8">
       <div class="well">
         
         
        <% @posts.each do |post| %>
        <div id="post_show_content" class="skinny_wrapper wrapper_padding">
        	<header>
        		<p class="date"><%=time_ago_in_words(post.created_at)%> ago</p>
        		<h1><%=post.title%></h1>
        		<p class="date"><%=post.user.name%> tarafından yayınlandı</p>
        		<p><%=post.category.name%> bölüne ait</p>
        		<hr >
        	</header>
       
        <h5>
            <span class="glyphicon glyphicon-thumbs-up"></span> (<%=post.likes.count%>) beğeni&nbsp;  
            <% if post.comments.count>0 %>
                      <span class="glyphicon glyphicon-comment"></span>
                     (<%= post.comments.count%>) yorum 
             <%end%>    
        </h5>
                         
        	<div id="content">
        	<%=image_tag post.image.url(:medium),class:"img img-responsive" if post.image?%>  
        	<p><%= markdown post.msg%></p>
        	<div class="show-more">
             <%=link_to 'Devamını Oku',post%>
           </div>
           
        <div class="action">
            <div id="<%=post.id%>">
                    <%if Like.where(user:current_user, post:post).count>0%>
                        <%= link_to "", unlike_post_path(post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>
                       
                    <%else%>
                        <%= link_to "", like_post_path(post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>
                       
                    <%end%>
            </div>
        </div>
        
           <br>
            <%= link_to 'Yorumları Göster ', post ,class:'fa fa-eye'%>
        </div>
        <div id="share_box">
        	<p>Paylaş</p>
        	
        	<a onclick="javascript:window.open('http://twitter.com/share?text=<%= post.title %> by Mehmet Yılmaz- url=<%= url_for([post, {only_path:false}]) %>',
            '_blank', 'width=800, height=500, top=200, left=300');void(0)">
            <i class="fa fa-twitter"></i></a>
            
            <a onclick="javascript:window.open('http://facebook.com/sharer.php?u=<%= post.title %> by Mehmet Yılmaz- url=<%= url_for([post, {only_path:false}]) %>',
            '_blank', 'width=800, height=500, top=200, left=300');void(0)">
            <i class="fa fa-facebook"></i></a>
            
            <a onclick="javascript:window.open('http://plus.google.com/share?url=<%= url_for([post, {only_path:false}]) %>',
            '_blank', 'width=800, height=500, top=200, left=300');void(0)">
            <i class="fa fa-google-plus"></i></a>

        </div>
        </div>
      <hr>
      <%end%> 
      <div align="center">
          <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
      </div>
      </div>
    </div>
	  <div class="col-md-4">
	    <div class="well">
	        <div id="custom-search-input">
                <div class="input-group col-md-12">
                    <input type="text" class="form-control input-lg" placeholder="arayın..." />
                    <span class="input-group-btn">
                        <button class="btn btn-info btn-lg" type="button">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>
                </div>
            </div>
           <hr> 
          <p align="center">
            &nbsp;<a class="btn btn-primary social-login-btn" href="https://www.facebook.com/mmt3d"><i class="fa fa-facebook"></i></a>
            <a class="btn btn-primary social-login-btn" href="https://twitter.com/mmt3d"><i class="fa fa-twitter"></i></a>
            <a class="btn btn-primary social-login-btn" href="https://tr.linkedin.com/mmt3d"><i class="fa fa-linkedin"></i></a>
            <a class="btn btn-primary social-login-btn" href="https://plus.google.com/u/0/+MehmetY%C4%B1lmazxd"><i class="fa fa-google-plus"></i></a>
          </p>
          <hr>
              	<div class="col-md-12" align="center">
                        <img src="https://scontent-frt3-2.xx.fbcdn.net/v/t1.0-9/26903639_10156087790553624_4729927528095548795_n.jpg?_nc_cat=0&oh=4aaccf59dda6e759b1c7525c89db5cb5&oe=5B94BE82" id="img-logom" class="img-circle" alt="aboutme">
                        <p></p>
                        <p align="center">Mehmet Yılmaz | Fırat Üniversitesi</p>
                        <p></p>
                </div>  
          <hr>
           <% @g1='Genel Yazılar'%>
          
          <div class="col-md-12">
            <div id="sidebar" class="well sidebar-nav">
                <h5><i class="glyphicon glyphicon-qrcode"></i>
                    <small><b>PROGRAMMING</b></small>
                </h5>
                <ul class="nav nav-pills nav-stacked">
                  <% @cat[1..(@cat.count)-1].each do |cat| %>
                      <li><a href="posts?category=<%=cat.name%>"><%=cat.name%>(<%=Post.where(category_id: Category.find_by(name: cat.name)).count %>)</a></li>
                  <%end%> 
                </ul>
                <h5><i class="glyphicon glyphicon-edit"></i>
                    <small><b>GENEL</b></small>
                </h5>
                <ul class="nav nav-pills nav-stacked">
                    <li><a href="/posts?category=Genel+Yazılar"><%=@g1%> (<%=Post.where(category_id: Category.find_by(name:@g1)).count %>)</a></li>
                </ul>
            </div>
        </div>
        
        <hr>
        <div class="homepage_content">
          <hr>
          		<h2>Yazılar</h2>
                  <hr>
                   <% @posts2.each do |post| %>
                      <p><%= link_to post.title, post %></p>
                  <%end%> 
          </div>
          <hr>
        
	    </div>  
	  </div>
	  
  </div>
</div>

<p id="notice"><%= notice %></p>
<%= render 'shared/footer'%>

app/views/posts/like.js.erb
$('#<%=@post.id%>').html('<%= link_to "", unlike_post_path(@post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>')

app/views/posts/new.html.erb
<div class="container"><br>
   <div class="well">
     <%= render 'form' %>
    </div>      
</div> 

<%= render 'shared/footer'%>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="row">
  	 <div class="col-md-2">
	  </div>
    <div class="col-md-8">
       <div class="well">
        <div id="post_show_content" class="skinny_wrapper wrapper_padding">
        	<header>
        		<p class="date"><%=@post.created_at%> </p>
        		<h1><%=@post.title%></h1>
        		<p class="date"><%=@post.user.name%> tarafından yayınlandı</p>
        		<div class="col-md-12">
                        <%=image_tag @post.user.image.url(:thumb),class:"img-circle" if @post.user.image?%>
                </div><br>   
        		<hr>
        	</header>
        	<div id="content">
        	<%=image_tag @post.image.url(:medium),class:"img img-responsive" if @post.image?%>  
        	<p><%= markdown @post.msg%></p>
           <br>
           <% if current_user==@post.user%>
              <%= link_to 'Düzenle ', edit_post_path(@post) ,class:'fa fa-pencil'%>
            
              <%= link_to 'Sil ', @post, class:'fa fa-trash-o',method: :delete, data: { confirm: 'Are you sure?' } %></p>
           <%end%>  
           
        </div>
        <div id="share_box">
        	<p>Paylaş</p>
        	<a href="#"><i class="fa fa-facebook"></i></a>
        	<a href="#"><i class="fa fa-twitter"></i></a>
        	<a href="#"><i class="fa fa-google-plus"></i></a>
        </div>
        
      <hr>
        <br>  
        <div class="action">
            <div id="<%=@post.id%>">
                    <%if Like.where(user:current_user, post:@post).count>0%>
                        <%= link_to "", unlike_post_path(@post), class:"glyphicon glyphicon-heart",remote: :true, method: :put %>
                        (<%=@likeds.count%>) kişi beğendi <p></p>
                    <%else%>
                        <%= link_to "", like_post_path(@post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>
                        (<%=@likeds.count%>) kişi beğendi <p></p>
                    <%end%>
            </div>
        </div>
                        
        

            <div id="comments">
               <%@comments.each do |c|%>
                    <div class="container">
                            <div class="media">
                        <div class="media-left">
                                <%=image_tag c.user.image.url(:thumb),class:"media-object",style:"width:45px" if c.user.image?%> 
                        </div>
                        <div class="media-body">
                                <h4 class="media-heading"><%=c.user.name%><small><i><%=c.created_at%></i></small></h4>
                                <p><%=c.bdy%></p>
                        </div>
                            </div>
                            <br>
                    </div>
                <%end%>
            </div>
            <% if user_signed_in? %>
				<%=render 'comments/form'%>
			<%end%>	
      
       </div>
      </div>
    </div>
	  <div class="col-md-2">
	  </div>
	  
  </div>
</div>

<p id="notice"><%= notice %></p>
<%= render 'shared/footer'%>

app/views/posts/unlike.js.erb
$('#<%=@post.id%>').html('<%= link_to "", like_post_path(@post), class:"glyphicon glyphicon-heart-empty",remote: :true, method: :put %>')

app/views/shared/_footer.html.erb
<footer id="main_footer">
	<p class="copyright">&copy;2018 Mehmet Yılmaz <i class="fa fa-maxcdn" style="font-size:24px"></i></p>
	<nav >
		<a href="https://facebook.com/mmt3d"><i class="fa fa-facebook-square" aria-hidden="true" style="font-size:25px"></i></a>
		<a href="https://youtube.com/mmt3d"><i class="fa fa-youtube-square" style="font-size:25px;color:red"></i></i></a>
		<a href="https://github.com/ylmazmehmet60"><i class="fa fa-github-square" aria-hidden="true" style="font-size:25px"></i></a>
	</nav>
</footer>	

app/views/shared/_nav.html.erb
<header id="main_navigation" class="clearfix">
	<a href="/posts" class="name">THEYILMAZ'S </a>
	<nav>
    	&emsp;&emsp;&emsp;
    	<%= link_to 'Yayınlar',root_path%>
    	<%= link_to 'İçerik Yükle',new_post_path %>
    	<%= link_to 'Hakkımda',aboutme_index_path %>
		<a href="/aboutme/contact">İletişim</a>
		
		<ul class="nav navbar-right">
            <% if user_signed_in? %>
            <em><%=image_tag current_user.image.url(:mini) ,:class=>'img-circle' %> </em>
            Hoşgeldin <%= current_user.name %>&emsp;
            <%= link_to 'Hesabım', edit_user_registration_path, :class=>'glyphicon glyphicon-user'%> |
            <%= link_to 'Çıkış Yap', destroy_user_session_path, method: :delete, :class=>'glyphicon glyphicon-log-out'%>
            <% else %>
            <%= link_to ' Üye Ol', new_user_registration_path, :class=>'glyphicon glyphicon-user' %> 
            <%= link_to ' Oturum Aç', new_user_session_path, :class=>'glyphicon glyphicon-log-in'%></a>
            <%end%>
        </ul>    
	</nav>
</header>